# Generated by Django 3.1.1 on 2020-09-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, null=True, upload_to='myphoto/%Y/%m/%d/')),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='particular_work',
            field=models.JSONField(null=True),
        ),
    ]
