# Generated by Django 3.1.1 on 2020-09-13 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('end_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='crated_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='crated_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='crated_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='crated_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='jobcard',
            old_name='discount',
            new_name='additional_discount',
        ),
        migrations.RenameField(
            model_name='jobcard',
            old_name='crated_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='masterservice',
            old_name='crated_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='crated_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='photogallary',
            old_name='crated_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='crated_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='serviceenquiy',
            old_name='crated_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='crated_date',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='billing',
            name='discount',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
