# Generated by Django 3.1.1 on 2020-09-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user', '0002_auto_20200915_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photogallary',
            name='image_file',
            field=models.ImageField(max_length=255, null=True, upload_to='myphoto/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_file',
            field=models.ImageField(max_length=255, null=True, upload_to='myphoto/%Y/%m/%d/'),
        ),
    ]
