# Generated by Django 3.1.1 on 2020-09-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('end_user', '0003_auto_20200915_1950'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyPhoto',
        ),
    ]
