# Generated by Django 3.1.1 on 2020-10-18 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('end_user', '0005_auto_20201016_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceenquiry',
            name='Service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='end_user.service'),
        ),
        migrations.AlterField(
            model_name='serviceenquiry',
            name='enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_enquiry', to='end_user.enquiry'),
        ),
    ]
